######################################################################
##
## Filename: MATRIX_CTRL.udo
## Created on: Sat Jan 28 16:17:35 W. Europe Standard Time 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
