######################################################################
##
## Filename: STOSAvectorial_tb.udo
## Created on: Wed Nov 16 12:12:18 W. Europe Standard Time 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
